### ISSUE TITLE
Confirma crashes immediately on start

### ISSUE THREAD

**Issue by OpalSoPL** [MASSHUU12/godot-confirma#158]
### Describe the bug

Confirma crashes game immediately after start
tests do not run either

### Steps to reproduce

1. open project with enabled confirma
2. run project

### Expected behavior

so that confirma does not cause the game to crash and the tests work.

### Additional information

- OS: Linux Mint 21.3
- Version: 0.8.0 (from AssetLib)
- Godot version: 4.3 mono
- .NET version: 8.0.108

**Comment by MASSHUU12** [comment]
You are right, yet it is not a crash, but the game just shuts down. The tests actually do not work. Whether the tests are or not, the same error is thrown, which is strange because it only occurs when the plugin is downloaded from AssetLib. I will try to fix this as soon as possible.

**Comment by OpalSoPL** [comment]
when I tested the git version this also happened

**Comment by MASSHUU12** [comment]
I was able to fix the tests not starting, the problem occurs when there are no GDScript tests because `private List<TestLog>? _testLogs;` is never created, which causes a NullReferenceException. Now I'm taking on the first problem.

**Comment by MASSHUU12** [comment]
Can you check if this https://github.com/MASSHUU12/godot-confirma/pull/159 PR fixed the issue?

**Comment by OpalSoPL** [comment]
fixed
