### ISSUE TITLE
Assertion 'ConfirmEqual' prints `null` as empty string in default message

### ISSUE THREAD

**Issue by MASSHUU12** [MASSHUU12/godot-confirma#167]
### Describe the bug

Assertion 'ConfirmEqual' prints `null` as empty string in default message.

### Steps to reproduce

Run:

```cs
_ = "".ConfirmEqual(null);
```

See error:

```txt
Expected '' but got ''.
```

### Expected behavior

The displayed error message should print `null` as null and not an empty string.

### Additional information

N/A

**Comment by OpalSoPL** [comment]
Update:
After merging #169
Running the same code, returns error:
```
Assertion ConfirmEqual failed: Expected , but got ""
```
