### ISSUE TITLE
[GDScript] Method names in verbose mode display "([])" when there are no arguments

### ISSUE THREAD

**Issue by MASSHUU12** [MASSHUU12/godot-confirma#213]
### Describe the bug

Method names in verbose mode display "([])" when there are no arguments:

```txt
[GDScript] ConfirmVectorWrapperTest...
 | confirm_equal_approx_when_equal_approx([])... passed.
 | confirm_not_equal_approx_when_not_equal_approx([])... passed.
...
```

### Steps to reproduce

Run tests with '--confirma-verbose' option.

### Expected behavior

Method names in verbose mode without arguments should not display "([])":

```txt
[GDScript] ConfirmVectorWrapperTest...
 | confirm_equal_approx_when_equal_approx... passed.
 | confirm_not_equal_approx_when_not_equal_approx... passed.
...
```

### Additional information

N/A

**Comment by OpalSoPL** [comment]
probably related with: `CollectionHelper` class

**Comment by MASSHUU12** [comment]
> probably related with: `CollectionHelper` class

You are right, and your commit will allow simplifying ` TestCase.cs` which now looks like this:

```cs
        Params = parameters is not null && parameters.Length != 0
            ? CollectionHelper.ToString(parameters, addBrackets: false)
            : string.Empty;
```
